# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-14
spec:
  selector:
    matchLabels:
      app: module-14
  replicas: 1
  template:
    metadata:
      labels:
        app: module-14
    spec:
      containers:
        - name: todo
          image: todo-app:prod
          ports:
            - containerPort: 80
          imagePullPolicy: Never
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: SECRET_KEY
            - name: LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: log-level
                  key: LOG_LEVEL
            - name: LOGGLY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: loggly-token
                  key: LOGGLY_TOKEN
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth-client-id
                  key: OAUTH_CLIENT_ID
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth-client-secret
                  key: OAUTH_CLIENT_SECRET
            - name: MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: mongodb-connection-string
                  key: MONGODB_CONNECTION_STRING
            - name: MONGODB_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-database-name
                  key: MONGODB_DATABASE_NAME
